### ISSUE TITLE
Weird behaviour when checking property from an interface (not from a package)

### ISSUE THREAD

**Issue by vperrin59** [tudortimi/vgm_svunit_utils#1]
I had some strange behaviour when using FAIL_UNLESS_PROP_FAIL macro with a property defined in an interface with Xcelium 19.03

When using the property from a package the expect statement failed the test correctly passes.

When using the same property from an interface, the expect statement failed but the test does not pass.

I could try to give the test case if desired

**Comment by vperrin59** [comment]
I investigated further and it looks like a tool issue (Cadence). I tried other tools (through EDAPlayground) but the results were not so much better. Only Aldec showed some correct behaviour

**Comment by tudortimi** [comment]
I've seen this as well. Unfortunately, we can't do anything about it.

**Comment by vperrin59** [comment]
Right, I created a ticket with the Cadence support. Let's see if they spend some time trying to fix that.
